version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--requirepass", "AudR@red4312", "--notify-keyspace-events", "Kgl"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "AudR@red4312", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  tcp-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network
    restart: on-failure
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9000"]
      interval: 5s
      timeout: 5s
      retries: 5

  tcp-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - tcp-server
    environment:
      - CHUNK_DELAY=1000
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge
