---
# docker-compose.yml
#version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--requirepass", "AudR@red4312"]
    ports:
      - "6379:6379"
    networks:
      - app-network

  tcp-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "9300:9300"
    env_file:
      - ${ENV_FILE:-.env}
    depends_on:
      - redis
    networks:
      - app-network
    restart: on-failure
    # healthcheck:
    #   test: ["CMD", "nc", "-z", "localhost", "9300"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 5

  tcp-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - tcp-server
    environment:
      - CHUNK_DELAY=1000
      - CLIENT_COUNT=100
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge