# Dockerfile.server

FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Copy wait-for script
COPY wait-for.sh /usr/local/bin/wait-for.sh
RUN chmod +x /usr/local/bin/wait-for.sh

CMD ["wait-for.sh", "redis:6379", "--", "node", "src/socket-server.js"]