name: build-and-test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Images
        run: docker-compose build

      - name: Run Docker Containers
        run: docker-compose up -d

      - name: Wait for TCP Server to be ready
        run: |
          for i in {1..10}; do
            if docker exec $(docker ps -qf "name=tcp-server") nc -z localhost 9000; then
              echo "✅ TCP server is ready"
              exit 0
            fi
            echo "⏳ Waiting for TCP server on port 9000..."
            sleep 3
          done
          echo "❌ TCP Server failed to start on port 9000" && exit 1

      - name: Run Jest Unit Tests
        run: |
          docker exec $(docker ps -qf "name=tcp-server") npx jest --coverage

      - name: List Running Containers
        run: docker ps

      - name: Shutdown
        if: always()
        run: docker-compose down --volumes --remove-orphans
