name: build-and-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Images
        run: docker compose build

      - name: Run Docker Containers
        run: docker compose up -d

      - name: Print TCP Server Logs
        run: |
          docker logs $(docker ps -qf "name=tcp-server")

      - name: Wait for TCP Server to be ready
        run: |
          echo "Checking if TCP server is accepting connections on port 9300..."
          for i in {1..60}; do
            echo "Waiting for port 9300..."
            timeout 1 bash -c '</dev/tcp/127.0.0.1/9300' 2>/dev/null && echo "✅ Port 9300 open" && exit 0
            sleep 2
          done
          echo "❌ Port 9300 not open"
          exit 1


      - name: Run Jest Unit Tests
        run: |
          docker exec $(docker ps -qf "name=tcp-server") npm test

      - name: List Running Containers
        run: docker ps -a

      - name: Shutdown
        run: docker compose down --volumes --remove-orphans

      - name: Print All Container Logs (Debug)
        run: |
          docker ps -a
          docker logs $(docker ps -aqf "name=tcp-server") || true
