name: build-and-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Images
        run: docker compose build

      - name: Run Docker Containers
        run: docker compose up -d

      - name: Wait for TCP Server to be ready
        run: |
          for i in {1..10}; do
            echo "Waiting for port 9300..."
            nc -zv 127.0.0.1 9300 && exit 0 || sleep 3
          done
          echo "\u274C Port 9300 not open"
          exit 1

      - name: Run Jest Unit Tests
        run: |
          docker exec $(docker ps -qf "name=tcp-server") npm test

      - name: List Running Containers
        run: docker ps -a

      - name: Print TCP Server Logs
        run: |
          docker logs $(docker ps -qf "name=tcp-server")

      - name: Shutdown
        run: docker compose down --volumes --remove-orphans

      - name: Print All Container Logs (Debug)
        run: |
          docker ps -a
          docker logs $(docker ps -aqf "name=tcp-server") || true