name: build-and-test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub (Optional)
        if: false
        run: echo "Skipping login step unless needed"

      - name: Build Docker Images
        run: docker compose build

      - name: Run Docker Containers
        run: docker compose up -d

      - name: Wait for TCP Server to be ready
        run: |
          for i in {1..10}; do
            echo "Waiting for port 9000..."
            nc -zv 127.0.0.1 9000 && echo "✅ Port 9000 is open" && exit 0
            sleep 3
          done
          echo "❌ Port 9000 not open"
          exit 1

      - name: List Running Containers
        run: docker ps

      - name: Run Jest Unit Tests
        run: |
          docker compose exec -T tcp-server npm test

      - name: Print TCP Server Logs
        if: failure()
        run: docker logs $(docker ps -aqf "name=tcp-server")

      - name: Shutdown
        if: always()
        run: docker compose down --volumes --remove-orphans
