name: Docker TCP Server CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Images
        run: docker compose build

      - name: Run Docker Containers
        run: docker compose up -d && sleep 10

      - name: List Running Containers
        run: docker ps

      - name: Check TCP Server Health (port 9000)
        run: |
          nc -zv 127.0.0.1 9000 || (echo "Port 9000 not open" && exit 1)

      - name: Shutdown
        run: docker compose down
